export const Banners = [
  {
    bannerPhotoURL:
      'https://static.vecteezy.com/system/resources/previews/004/664/959/original/advertising-web-banner-business-card-template-marketing-company-contact-page-with-phone-email-linear-icons-print-display-online-ads-presentation-web-page-idea-corporate-design-layout-vector.jpg',
  },
  {
    bannerPhotoURL:
      'https://static.vecteezy.com/system/resources/previews/004/664/959/original/advertising-web-banner-business-card-template-marketing-company-contact-page-with-phone-email-linear-icons-print-display-online-ads-presentation-web-page-idea-corporate-design-layout-vector.jpg',
  },
  {
    bannerPhotoURL:
      'https://static.vecteezy.com/system/resources/previews/004/664/959/original/advertising-web-banner-business-card-template-marketing-company-contact-page-with-phone-email-linear-icons-print-display-online-ads-presentation-web-page-idea-corporate-design-layout-vector.jpg',
  },
  {
    bannerPhotoURL:
      'https://static.vecteezy.com/system/resources/previews/004/664/959/original/advertising-web-banner-business-card-template-marketing-company-contact-page-with-phone-email-linear-icons-print-display-online-ads-presentation-web-page-idea-corporate-design-layout-vector.jpg',
  },
  {
    bannerPhotoURL:
      'https://static.vecteezy.com/system/resources/previews/004/664/959/original/advertising-web-banner-business-card-template-marketing-company-contact-page-with-phone-email-linear-icons-print-display-online-ads-presentation-web-page-idea-corporate-design-layout-vector.jpg',
  },
  {
    bannerPhotoURL:
      'https://static.vecteezy.com/system/resources/previews/004/664/959/original/advertising-web-banner-business-card-template-marketing-company-contact-page-with-phone-email-linear-icons-print-display-online-ads-presentation-web-page-idea-corporate-design-layout-vector.jpg',
  },
]
